/* DSA workspace uses the existing account, completion, editor and runner services. */
(async function () {
  if (/^#dsa-\d/.test(location.hash)) { location.replace('dsa-legacy.html' + location.hash); return; }
  const root = document.getElementById('dsa-root');
  document.querySelector('.dsa-skip').onclick = event => { event.preventDefault(); document.getElementById('dsa-main').focus(); };
  const scripts = new Map(), lessonCache = new Map();
  let catalog, routeVersion = 0, timeline = null, currentLesson = null, editor = null, currentProblem = null, usedHints = 0, attempts = 0, lastError = '';
  const html = value => esc(String(value ?? ''));
  const prose = value => String(value || '').split(/\n\n+/).map(paragraph=>`<p>${html(paragraph)}</p>`).join('');
  const button = (label,attr='') => `<button type="button" class="btn" ${attr}>${html(label)}</button>`;
  function loadScript(name) {
    if (!scripts.has(name)) scripts.set(name,new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='../js/'+name+'.js';script.onload=resolve;script.onerror=()=>{scripts.delete(name);reject(new Error('Could not load '+name));};document.head.append(script);}));
    return scripts.get(name);
  }
  async function api(path,options){const response=await fetch('/api/dsa/'+path,options);const body=await response.json();if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:body.error||'Request failed');return body;}
  async function lesson(id){if(!lessonCache.has(id))lessonCache.set(id,await api('lessons/'+encodeURIComponent(id)));return lessonCache.get(id);}
  const topic = id => catalog.topics.find(item=>item.id===id);
  const complete = id => Progress.isDone(topic(id)?.legacyId || id);
  const title = id => topic(id)?.title || id;
  function topicLink(id){const item=topic(id);return `<a href="#topic/${encodeURIComponent(id)}">${html(item?.title||id)}</a>`;}
  function card(item){const ready=DSAStore.ready(item,complete);return `<article class="dsa-card"><h3>${topicLink(item.id)}</h3><div class="dsa-meta"><span class="dsa-badge">${html(item.difficulty)}</span><span>${item.minutes?item.minutes+' min':''}</span><span>${complete(item.id)?'Completed':html(item.status)}</span></div><p>${html(item.description||item.summary||'')}</p><p class="dsa-muted">${ready?'Prerequisites covered': 'Prerequisites: '+(item.prerequisites||[]).filter(id=>!complete(id)).map(title).join(', ')}</p></article>`;}
  function masteryHTML(id){return '<div class="dsa-mastery">'+Object.entries(DSAStore.mastery(id)).map(([dimension,value])=>`<div><strong>${dimension}</strong><p>${value.count?value.passed+'/'+value.count+' evidence checks':'Not assessed'}</p>${value.count?`<meter min="0" max="100" value="${value.score}" aria-label="${dimension} assessment success"></meter>`:''}<span class="dsa-evidence">${value.due?'Review due':''}${value.selfReported?' · Includes self-assessment':''}</span></div>`).join('')+'</div>';}
  function record(dimension,id,passed,source){DSAStore.record(currentLesson.id,dimension,id,passed,source);const box=root.querySelector('[data-mastery]');if(box)box.innerHTML=masteryHTML(currentLesson.id);}
  function home(){const state=DSAStore.read(),next=DSAStore.recommendations(catalog,complete).slice(0,4),recent=[...new Set(state.activity.map(item=>item.topic))].filter(id=>topic(id)).slice(0,4),reviews=DSAStore.reviews();
    root.innerHTML=`<h2>Your learning workspace</h2><p class="dsa-prose">Completion records what you have studied. Mastery records what you can demonstrate. Start with prerequisites, then trace and implement each idea.</p><div class="dsa-grid"><article class="dsa-card"><h3>Continue learning</h3>${recent.length?recent.map(id=>`<p>${topicLink(id)}</p>`).join(''):'<p>No study activity yet. Choose a prerequisite-ready topic below.</p>'}</article><article class="dsa-card"><h3>Review today</h3>${reviews.length?reviews.slice(0,6).map(item=>`<p>${topicLink(item.topic)} · ${html(item.dimension)}${item.passed?'':' · previous mistake'}</p>`).join(''):'<p>No assessments due. Quizzes and trace predictions create review evidence.</p>'}</article><article class="dsa-card"><h3>Current path</h3><p>${html(catalog.paths.find(path=>path.id===state.path)?.title||'Choose a learning path')}</p><a href="#paths">View paths</a><p>${Object.keys(state.library).length} saved resources · <a href="#library">My library</a></p></article></div><h2>Recommended next</h2><div class="dsa-grid">${next.map(card).join('')||'<p>You have covered all currently published prerequisites and lessons.</p>'}</div><h2>Published learning units</h2><div class="dsa-grid">${catalog.topics.filter(item=>item.status==='published').map(card).join('')}</div><p><a href="#curriculum">Explore the complete curriculum map</a> · <a href="dsa-legacy.html">Original DSA lessons</a></p>`;
  }
  function curriculum(){
    root.innerHTML=`<h2>Curriculum</h2><p>Explore a prerequisite-aware hierarchy. Published lessons are ready to study; planned topics identify curriculum work still to come. Cross-listed topics share one progress record.</p><div class="dsa-toolbar"><label>Search topics<input data-search type="search" placeholder="Topic or alias"></label><label>Difficulty<select data-difficulty><option value="">All levels</option>${['Foundation','Beginner','Intermediate','Advanced','Expert'].map(value=>`<option>${value}</option>`).join('')}</select></label><label>Status<select data-status><option value="">All topics</option><option value="published">Published</option><option value="legacy">Original lessons</option><option value="planned">Planned</option><option value="unresolved">Awaiting definition</option><option value="completed">Completed</option></select></label></div><p data-result-count role="status"></p><div data-results></div>`;
    function update(){
      const q=root.querySelector('[data-search]').value.trim().toLowerCase(),difficulty=root.querySelector('[data-difficulty]').value,status=root.querySelector('[data-status]').value;
      const list=catalog.topics.filter(item=>(!q||JSON.stringify([item.title,item.aliases]).toLowerCase().includes(q))&&(!difficulty||item.difficulty===difficulty)&&(!status||(status==='completed'?complete(item.id):item.status===status)));
      function branch(category,depth){
        const items=list.filter(item=>item.category===category.id||(item.categories||[]).includes(category.id));
        const children=catalog.categories.filter(child=>child.parent===category.id).map(child=>branch(child,depth+1)).join('');
        if(!items.length&&!children)return '';
        const body=(items.length?`<div class="dsa-grid">${items.map(card).join('')}</div>`:'')+children;
        if(depth)return `<details class="dsa-category" ${q||difficulty||status?'open':''}><summary>${html(category.title)}</summary>${body}</details>`;
        return `<section class="dsa-category"><h2>${html(category.title)}</h2>${body}</section>`;
      }
      root.querySelector('[data-result-count]').textContent=`${list.length} matching topics. Expand a structure family to explore its lessons.`;
      root.querySelector('[data-results]').innerHTML=catalog.categories.filter(category=>!category.parent).map(category=>branch(category,0)).join('')||'<p>No matching topics.</p>';
    }
    root.querySelectorAll('input,select').forEach(el=>el.oninput=update);update();
  }
  function paths(){
    const selected=DSAStore.read().path;
    root.innerHTML='<h2>Prerequisite-aware learning paths</h2><p>Choosing a path prioritizes its available prerequisites in Recommended next. It does not mark topics complete or unlock unavailable lessons.</p>'+catalog.paths.map(path=>`<section class="dsa-panel"><h3>${html(path.title)}</h3><p>${html(path.description)}</p><p>${path.topics.filter(complete).length} / ${path.topics.length} topics completed</p><div class="dsa-path">${path.topics.map((id,i)=>`${i?' → ':''}${topicLink(id)} ${complete(id)?'✓':''}`).join('')}</div>${button(selected===path.id?'Current path':'Use this path',`data-path="${html(path.id)}" aria-pressed="${selected===path.id}"`)}</section>`).join('');
    root.querySelectorAll('[data-path]').forEach(el=>el.onclick=()=>{DSAStore.path(el.dataset.path);paths();toast('Learning path selected');});
  }
  function comparisons(id){
    const items=catalog.comparisons||[];
    root.innerHTML=`<h2>Compare structures and algorithms</h2><p>Choose by the operation contract, input assumptions and resource budget. Bounds below state their representation assumptions; a faster asymptotic bound alone does not decide an engineering tradeoff.</p><label>Comparison<select data-comparison>${items.map(item=>`<option value="${html(item.id)}">${html(item.title)}</option>`).join('')}</select></label><div data-comparison-body></div>`;
    const select=root.querySelector('[data-comparison]');
    if(items.some(item=>item.id===id))select.value=id;
    function draw(){const item=items.find(item=>item.id===select.value);if(!item)return;
      root.querySelector('[data-comparison-body]').innerHTML=`<section class="dsa-panel"><h3>${html(item.title)}</h3><div class="dsa-scroll" tabindex="0" role="region" aria-label="${html(item.title)} comparison table"><table><caption>${html(item.title)} — assumptions and tradeoffs</caption><thead><tr><th scope="col">Criterion</th>${item.topics.map((id,i)=>`<th scope="col">${html(item.labels?.[i]||title(id))}</th>`).join('')}</tr></thead><tbody>${item.rows.map(row=>`<tr><th scope="row">${html(row.label)}</th>${row.values.map(value=>`<td>${html(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><h4>How to choose</h4>${prose(item.guidance)}<p>${item.topics.map(topicLink).join(' · ')}</p><p><a href="#memory">Inspect memory tradeoffs</a> · <a href="#complexity">Compare growth</a> · <a href="#lab">Trace an available algorithm</a></p></section>`;
    }
    select.onchange=()=>{history.replaceState(null,'','#compare/'+encodeURIComponent(select.value));draw();};draw();
  }
  function patterns(){root.innerHTML='<h2>Problem-solving patterns</h2><p>Choose a technique from its preconditions, not from a familiar problem title.</p>'+catalog.patterns.map(pattern=>`<section class="dsa-panel"><h3>${html(pattern.title)}</h3><h4>Recognition clues</h4>${prose(Array.isArray(pattern.clues)?pattern.clues.join('\n'):pattern.clues)}<h4>Mental model</h4>${prose(pattern.model)}<pre>${html(pattern.template)}</pre><h4>Example</h4>${prose(pattern.example)}<h4>Common mistakes</h4>${prose(Array.isArray(pattern.mistakes)?pattern.mistakes.join('\n'):pattern.mistakes)}<p>${(pattern.topics||[]).map(topicLink).join(' · ')}</p></section>`).join('');}
  function graph(){root.innerHTML=`<h2>Knowledge graph</h2><p>Arrows point from prerequisites to the topic that depends on them. Related topics are alternatives or extensions, not required steps.</p><label>Focus topic<select data-focus>${catalog.topics.map(item=>`<option value="${html(item.id)}">${html(item.title)}</option>`).join('')}</select></label><div data-graph class="dsa-graph"></div>`;const select=root.querySelector('[data-focus]');function draw(){const item=topic(select.value),children=catalog.topics.filter(other=>(other.prerequisites||[]).includes(item.id));root.querySelector('[data-graph]').innerHTML=`<div class="dsa-grid"><section class="dsa-card"><h3>Prerequisites →</h3>${(item.prerequisites||[]).map(id=>`<p>${topicLink(id)}</p>`).join('')||'<p>Starting topic</p>'}</section><section class="dsa-card dsa-active"><h3>${html(item.title)}</h3><p>${html(item.status)} · ${html(item.difficulty)}</p>${topicLink(item.id)}</section><section class="dsa-card"><h3>→ Unlocks</h3>${children.map(child=>`<p>${topicLink(child.id)}</p>`).join('')||'<p>No published descendants yet.</p>'}</section></div><section class="dsa-card"><h3>Related concepts</h3>${(item.related||[]).map(topicLink).join(' · ')||'No related concepts recorded.'}</section>`;}select.onchange=draw;draw();}
  function notes(){const state=DSAStore.read();root.innerHTML='<h2>Notes &amp; bookmarks</h2><div class="dsa-grid">'+Object.entries(state.notes).filter(([,text])=>text).map(([id,text])=>`<article class="dsa-card"><h3>${topicLink(id.replace(/^topic:/,''))}</h3>${prose(text)}</article>`).join('')+'</div><h3>Bookmarks</h3>'+Object.entries(state.bookmarks).map(([key,value])=>`<p><a href="#topic/${encodeURIComponent(value.topic)}${value.kind==='frame'?'?bookmark='+encodeURIComponent(key):''}">${html(value.title||title(value.topic))}</a> ${button('Remove',`data-remove="${html(key)}"`)}</p>`).join('');root.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{DSAStore.bookmark(el.dataset.remove,null);notes();});if(!Object.keys(state.notes).length&&!Object.keys(state.bookmarks).length)root.innerHTML+='<p>Save notes and frames from a lesson to return to them here.</p>';}
  function resources(library=false){let page=0;root.innerHTML=`<h2>${library?'My library':'Curated learning resources'}</h2><p>Each recommendation specifies what to study, when to study it, and the intended outcome. Personal ratings and notes stay in your learning state.</p><div class="dsa-toolbar"><label>Search<input data-rq type="search"></label><label>Type<select data-rt><option value="">All types</option>${[...new Set(catalog.resources.map(item=>item.type))].map(value=>`<option>${html(value)}</option>`).join('')}</select></label><label>Language<select data-rl><option value="">All languages</option>${[...new Set(catalog.resources.map(item=>item.language))].map(value=>`<option>${html(value)}</option>`).join('')}</select></label></div><div data-resources></div><div class="dsa-toolbar">${button('Previous page','data-rprev')}${button('Next page','data-rnext')}<span data-rcount></span></div>`;
    function update(){const state=DSAStore.read(),q=root.querySelector('[data-rq]').value.toLowerCase(),type=root.querySelector('[data-rt]').value,language=root.querySelector('[data-rl]').value;const matches=catalog.resources.filter(item=>(!library||state.library[item.id])&&(!q||JSON.stringify(item).toLowerCase().includes(q))&&(!type||item.type===type)&&(!language||item.language===language));page=Math.min(page,Math.max(0,Math.ceil(matches.length/8)-1));root.querySelector('[data-resources]').innerHTML=matches.slice(page*8,page*8+8).map(item=>{const saved=state.library[item.id];return `<section class="dsa-panel" data-resource="${html(item.id)}"><h3>${html(item.title)}</h3><p class="dsa-muted">${html(item.author)} · ${html(item.type)} · ${html(item.language)} · ${html(item.cost)} · ${html(item.difficulty)}</p>${prose(item.description)}<p><strong>Study:</strong> ${html(Array.isArray(item.sections)?item.sections.join('; '):item.sections)}</p><p><strong>Outcomes:</strong> ${html((item.objectives||[]).join('; '))}</p><p><strong>Prerequisites:</strong> ${(item.prerequisites||[]).map(topicLink).join(' · ')||'None'}</p><p>${(item.topics||[]).map(topicLink).join(' · ')}</p>${item.url?`<a href="${html(item.url)}" target="_blank" rel="noopener noreferrer">Open external resource ↗</a>`:'<p>Awaiting source curation</p>'} ${button(saved?'Saved ✓':'Save to library','data-save')}${saved?`<div class="dsa-toolbar"><label>Study status<select data-lib="status">${['Want to Learn','Learning','Completed'].map(value=>`<option ${saved.status===value?'selected':''}>${value}</option>`).join('')}</select></label><label>Progress (%)<input data-lib="progress" type="number" min="0" max="100" value="${Number(saved.progress)||0}"></label><label>Usefulness (0 = unrated)<input data-lib="rating" type="number" min="0" max="5" value="${Number(saved.rating)||0}"></label></div><label><input data-lib="favorite" type="checkbox" ${saved.favorite?'checked':''}> Favorite</label><p><label>Tags<input data-lib="tags" value="${html(saved.tags||'')}"></label></p><p><label>Last position (page, chapter, timestamp)<input data-lib="position" value="${html(saved.position||'')}"></label></p><label>Personal notes<textarea data-lib="notes">${html(saved.notes||'')}</textarea></label><p data-saved role="status"></p>`:''}</section>`;}).join('')||'<p>No matching saved resources.</p>';root.querySelector('[data-rcount]').textContent=`${matches.length} resources · Page ${page+1}`;root.querySelector('[data-rprev]').disabled=page===0;root.querySelector('[data-rnext]').disabled=(page+1)*8>=matches.length;
      root.querySelectorAll('[data-resource]').forEach(section=>{const id=section.dataset.resource;section.querySelector('[data-save]').onclick=()=>{DSAStore.resource(id,{});update();};section.querySelectorAll('[data-lib]').forEach(field=>field.onchange=()=>{let value=field.type==='checkbox'?field.checked:field.value;if(field.type==='number')value=Math.max(0,Math.min(field.dataset.lib==='rating'?5:100,Number(value)||0));DSAStore.resource(id,{[field.dataset.lib]:typeof value==='string'?value.slice(0,12000):value});section.querySelector('[data-saved]').textContent='Saved';});});}
    root.querySelectorAll('[data-rq],[data-rt],[data-rl]').forEach(el=>el.oninput=()=>{page=0;update();});root.querySelector('[data-rprev]').onclick=()=>{page--;update();};root.querySelector('[data-rnext]').onclick=()=>{page++;update();};update();
  }
  async function showTopic(id,params,version){const item=topic(id);if(!item)throw new Error('Topic not found');
    if(item.status==='legacy'){location.replace('dsa-legacy.html#'+encodeURIComponent(item.legacyId||id));return;}
    if(item.status!=='published'){root.innerHTML=`<h2>${html(item.title)}</h2><p class="dsa-notice">${item.status==='unresolved'?'The source definition is unresolved. Fibonacci Tree will not be silently substituted with Fibonacci Heap.':'This is a first-class curriculum topic awaiting a complete learning unit. It is not counted as a published lesson.'}</p><p>${html(item.description||'')}</p><h3>Prerequisites</h3><p>${(item.prerequisites||[]).map(topicLink).join(' → ')||'Not yet specified'}</p><h3>Related concepts</h3><p>${(item.related||[]).map(topicLink).join(' · ')}</p><p><a href="#curriculum">Return to curriculum</a></p>`;return;}
    const data=await lesson(id);if(version!==routeVersion)return;currentLesson=data;DSAStore.visit(id);
    root.innerHTML=`<header><p class="dsa-eyebrow">${html(catalog.categories.find(category=>category.id===item.category)?.title||item.category)} / ${html(item.difficulty)}</p><h2>${html(data.title)}</h2><p class="dsa-prose">${html(data.summary)}</p><div class="dsa-meta"><span>${item.minutes} min focused study</span><span data-completion-status>${complete(id)?'Completed':'In progress'}</span></div><p><strong>Prerequisites:</strong> ${(item.prerequisites||[]).map(topicLink).join(' · ')||'None'}</p>${!DSAStore.ready(item,complete)?'<p class="dsa-notice">Some prerequisites are not marked complete. You may explore now; the prerequisite links above explain the background.</p>':''}<div class="dsa-toolbar">${button(complete(id)?'Mark incomplete':'Mark lesson complete','data-complete')}${button('Bookmark lesson','data-bookmark-lesson')}</div></header>
      <nav class="dsa-section-links" aria-label="Lesson sections"><a href="#" data-scroll="understand">Understand</a><a href="#" data-scroll="visualize">Visualize & trace</a><a href="#" data-scroll="implement">Implement</a><a href="#" data-scroll="complexity-section">Complexity</a><a href="#" data-scroll="practice-section">Practice</a><a href="#" data-scroll="quiz-section">Quiz</a><a href="#" data-scroll="mastery">Mastery</a><a href="#" data-scroll="tutor">Tutor</a></nav>
      <section id="understand"><h2>Learning objectives</h2><ul>${data.objectives.map(value=>`<li>${html(value)}</li>`).join('')}</ul>${data.sections.map((section,i)=>`<details ${i<2?'open':''}><summary>${html(section.title)}</summary><div class="dsa-prose">${prose(section.body)}</div></details>`).join('')}</section>
      <section id="visualize"><h2>Visualize &amp; trace</h2><div data-timeline>Loading shared timeline…</div></section>
      <section id="implement"><h2>Implementations</h2><p class="dsa-muted">Language switching preserves your place. Reference implementations are read-only; edit and test your solution in Practice below. Java and TypeScript are study references; the current runner executes Python, JavaScript and C++.</p><div class="dsa-tabs">${Object.keys(data.implementations).map((language,i)=>button(language,`data-language="${language}" aria-pressed="${i===0}"`)).join('')}</div><pre data-implementation></pre><details><summary>Language-independent pseudocode</summary><pre>${html(data.pseudocode)}</pre></details></section>
      <section id="complexity-section"><h2>Complexity and cost model</h2><div class="dsa-scroll"><table><thead><tr><th>Operation</th><th>Time</th><th>Auxiliary space</th><th>Why</th></tr></thead><tbody>${data.complexity.map(row=>`<tr><th>${html(row.operation)}</th><td>${html(row.time)}</td><td>${html(row.space)}</td><td>${html(row.why)}</td></tr>`).join('')}</tbody></table></div><p><a href="#complexity">Compare growth in the Complexity Lab</a> · <a href="#memory">Explore memory layout</a></p></section>
      ${(catalog.comparisons||[]).some(comparison=>comparison.topics.includes(id))?`<section><h2>Compare alternatives</h2><p>${catalog.comparisons.filter(comparison=>comparison.topics.includes(id)).map(comparison=>`<a href="#compare/${html(comparison.id)}">${html(comparison.title)}</a>`).join(' · ')}</p></section>`:''}
      <section id="practice-section"><h2>Practice</h2><div data-problems></div></section>
      <section id="quiz-section"><h2>Check your understanding</h2><div data-quiz class="dsa-quiz"></div></section>
      <section id="mastery"><h2>Mastery evidence</h2><p class="dsa-muted">Evidence success is not a certification score. Reading or completing this page does not award mastery. Trace predictions, code tests, quizzes and clearly labelled self-assessment contribute separately.</p><div data-mastery>${masteryHTML(id)}</div><details><summary>Self-assessment rubric</summary><p>Without looking at the solution, explain the invariant, prove termination, and compare this technique with an alternative. Self-reported evidence is labelled.</p><div class="dsa-toolbar"><label>Dimension<select data-self-dim>${['Explain','Analyze','Compare','Prove','Optimize'].map(value=>`<option>${value}</option>`).join('')}</select></label>${button('I can explain this unaided','data-self-pass')}${button('I need more practice','data-self-fail')}</div></details></section>
      <section><h2>Notes</h2><label>Personal lesson notes (plain text; Markdown can be stored as text)<textarea data-note>${html(DSAStore.read().notes['topic:'+id]||'')}</textarea></label>${button('Save note','data-note-save')}<p data-note-status role="status"></p></section>
      <section id="tutor"><h2>Contextual tutor</h2><p class="dsa-muted">Guided mode works without an AI service. If an external model is configured, pressing Ask sends the question, lesson, current trace, code, error and assessment context to that provider. Never include secrets in code or questions.</p><label>Mode<select data-tutor-mode><option value="explain">Explain</option><option value="socratic">Socratic</option><option value="hint">Hint</option><option value="exam">Exam</option></select></label><label>Question<textarea data-question maxlength="2000" placeholder="Why is this invariant preserved?"></textarea></label>${button('Ask','data-ask')}<p data-provider></p><div class="dsa-prose" data-answer role="status"></div></section>
      <section><h2>Resources and next steps</h2>${data.resources.map(resourceId=>{const resource=catalog.resources.find(item=>item.id===resourceId);return resource?`<p><a href="${html(resource.url)}" target="_blank" rel="noopener noreferrer">${html(resource.title)}</a> — ${html(resource.description)}</p>`:'';}).join('')}<p><a href="#resources">Browse and save resources to My Library</a></p><p><strong>Related:</strong> ${(item.related||[]).map(topicLink).join(' · ')}</p><p><strong>Ready next:</strong> ${DSAStore.recommendations(catalog,complete).filter(item=>item.id!==id).slice(0,4).map(item=>topicLink(item.id)).join(' · ')||'Review your assessments before continuing.'}</p></section>`;
    root.querySelectorAll('[data-scroll]').forEach(el=>el.onclick=event=>{event.preventDefault();document.getElementById(el.dataset.scroll).scrollIntoView({behavior:'auto'});});
    root.querySelector('[data-complete]').onclick=event=>{const done=!complete(id);const completionId=item.legacyId||id;Progress.setDone(completionId,done);if(done)XP.add(20,'lesson:'+completionId);event.target.textContent=done?'Mark incomplete':'Mark lesson complete';root.querySelector('[data-completion-status]').textContent=done?'Completed':'In progress';XP.renderPill();};
    root.querySelector('[data-bookmark-lesson]').onclick=()=>{DSAStore.bookmark('topic:'+id,{topic:id,kind:'topic',title:data.title});toast('Lesson bookmarked');};
    root.querySelector('[data-note-save]').onclick=()=>{try{DSAStore.note('topic:'+id,root.querySelector('[data-note]').value);root.querySelector('[data-note-status]').textContent='Saved on this device; account sync follows when signed in.';}catch(error){root.querySelector('[data-note-status]').textContent=error.message;}};
    for(const [attr,passed] of [['self-pass',true],['self-fail',false]])root.querySelector(`[data-${attr}]`).onclick=()=>{const dimension=root.querySelector('[data-self-dim]').value;record(dimension,'self-'+dimension,passed,'self-assessment');};
    const firstLanguage=Object.keys(data.implementations)[0];root.querySelector('[data-implementation]').textContent=data.implementations[firstLanguage];root.querySelectorAll('[data-language]').forEach(el=>el.onclick=()=>{root.querySelector('[data-implementation]').textContent=data.implementations[el.dataset.language];root.querySelectorAll('[data-language]').forEach(other=>other.setAttribute('aria-pressed',other===el));});
    bindQuiz(data);await bindProblems(data,version);if(version!==routeVersion)return;bindTutor(data);
    await Promise.all([loadScript('lab-viz'),loadScript('dsa-traces'),loadScript('dsa-timeline')]);if(version!==routeVersion)return;
    const bookmark=DSAStore.read().bookmarks[params.get('bookmark')];
    timeline=DSATimeline.mount(root.querySelector('[data-timeline]'),data.trace.kind,bookmark?.input||data.trace.input,id,record);if(bookmark?.frame!==undefined)timeline.seek(bookmark.frame);
  }
  function bindQuiz(data){
    const host=root.querySelector('[data-quiz]');
    host.innerHTML=data.quiz.map(question=>`<fieldset data-question-id="${html(question.id)}"><legend>${html(question.prompt)}</legend>${question.type==='multiple'?'<p class="dsa-muted">Select all that apply. Every selected and omitted option counts.</p>':''}${question.options.map((option,index)=>`<label><input type="${question.type==='multiple'?'checkbox':'radio'}" name="quiz-${html(question.id)}" value="${index}">${html(option)}</label>`).join('')}${button('Check answer','data-check')}<p data-quiz-feedback role="status"></p></fieldset>`).join('');
    host.querySelectorAll('fieldset').forEach(fieldset=>{
      const question=data.quiz.find(item=>item.id===fieldset.dataset.questionId),feedback=fieldset.querySelector('[data-quiz-feedback]');
      fieldset.querySelector('[data-check]').onclick=()=>{
        const choices=[...fieldset.querySelectorAll('input:checked')].map(input=>Number(input.value));
        if(!choices.length){feedback.textContent='Choose an answer first.';return;}
        const expected=question.type==='multiple'?question.answer:[question.answer];
        const passed=choices.length===expected.length&&choices.every(value=>expected.includes(value));
        record(question.dimension||'Explain','quiz-'+question.id,passed);
        feedback.textContent=(passed?'Correct. ':'Not quite. ')+question.explanation;
        fieldset.querySelector('[data-check]').disabled=true;fieldset.querySelectorAll('input').forEach(el=>{el.disabled=true;});
        if(passed){XP.add(5,'dsa-quiz:'+data.id+':'+question.id);XP.renderPill();}
      };
    });
  }
  async function bindProblems(data,version){await Promise.all([loadScript('runner'),loadScript('editor')]);if(version!==routeVersion)return;const host=root.querySelector('[data-problems]');host.innerHTML=`<label>Problem<select data-problem>${data.problems.map(problem=>`<option value="${html(problem.id)}">${html(problem.title)} · ${html(problem.difficulty)}</option>`).join('')}</select></label><div data-problem-body></div>`;
    function render(){const problem=data.problems.find(item=>item.id===host.querySelector('[data-problem]').value);currentProblem=problem;usedHints=0;attempts=0;lastError='';const body=host.querySelector('[data-problem-body]');body.innerHTML=`<h3>${html(problem.title)}</h3>${prose(problem.statement)}<p><strong>Constraints:</strong> ${html(Array.isArray(problem.constraints)?problem.constraints.join('; '):problem.constraints)}</p><pre>${html(problem.examples.join('\n'))}</pre><div class="dsa-toolbar"><label>Execution language<select data-run-language>${Object.keys(problem.starter).map(language=>`<option value="${language}">${language}</option>`).join('')}</select></label>${button('Run tests','data-run')}${button('Reset starter','data-reset')}${button('Reveal next hint','data-hint')}</div><div data-hints></div><div data-editor></div><div data-run-results role="status"></div><details><summary>Solution reasoning — attempt the problem first</summary>${Object.entries(problem.solution).map(([key,value])=>`<h4>${html(key)}</h4>${typeof value==='string'?prose(value):`<pre>${html(JSON.stringify(value,null,2))}</pre>`}`).join('')}</details>`;
      const select=body.querySelector('[data-run-language]');let language=select.value;const draftKey=()=>`martinium:draft:dsa:${problem.id}:${language}`;
      editor=CodeEditor.create(body.querySelector('[data-editor]'),{language,value:localStorage.getItem(draftKey())??problem.starter[language]});
      const save=()=>{localStorage.setItem(draftKey(),editor.getValue());window.Sync?.schedule();};body.querySelector('[data-editor] textarea').addEventListener('input',save);
      select.onchange=()=>{save();language=select.value;editor.setLanguage(language);editor.setValue(localStorage.getItem(draftKey())??problem.starter[language]);};
      body.querySelector('[data-reset]').onclick=()=>{editor.setValue(problem.starter[language]);save();};
      body.querySelector('[data-hint]').onclick=event=>{if(usedHints<problem.hints.length){const p=document.createElement('p');p.textContent=problem.hints[usedHints++];body.querySelector('[data-hints]').append(p);}event.target.disabled=usedHints>=problem.hints.length;};
      body.querySelector('[data-run]').onclick=async event=>{const runButton=event.target,code=editor.getValue(),runLanguage=language;save();attempts++;runButton.disabled=true;body.querySelector('[data-run-results]').textContent='Running…';try{const output=runLanguage==='cpp'?await Runner.cpp(code,problem.tests.cpp,problem.prelude||''):await Runner[runLanguage](code,problem.tests[runLanguage]);if(version!==routeVersion||currentProblem!==problem)return;lastError=output.error?JSON.stringify(output.error):'';const results=output.results||[],passed=!output.error&&results.length>0&&results.every(item=>item.pass);record('Implement','problem-'+problem.id,passed);const resultHost=body.querySelector('[data-run-results]');resultHost.innerHTML=`<p class="${passed?'dsa-success':'dsa-error'}">${passed?'All tests passed.':'Not all tests passed.'}</p><ul>${results.map(item=>`<li>${item.pass?'✓':'✗'} ${html(item.name)}${item.pass?'':' — expected '+html(item.expected)+', got '+html(item.actual)}</li>`).join('')}</ul><pre>${html(output.output||'')}${output.error?'\n'+html(lastError):''}</pre>`;if(passed){XP.add(15,'dsa-problem:'+problem.id);XP.renderPill();}}catch(error){lastError=error.message;body.querySelector('[data-run-results]').textContent=error.message;}finally{runButton.disabled=false;}};
    }host.querySelector('[data-problem]').onchange=render;if(data.problems.length)render();else host.innerHTML='<p>No coding problem attached to this lesson.</p>';
  }
  function bindTutor(data){root.querySelector('[data-ask]').onclick=async event=>{const button=event.target,question=root.querySelector('[data-question]').value.trim(),answer=root.querySelector('[data-answer]'),provider=root.querySelector('[data-provider]');if(!question){answer.textContent='Enter a question first.';return;}button.disabled=true;answer.textContent='Preparing guidance…';const version=routeVersion;try{const mastery=Object.fromEntries(Object.entries(DSAStore.mastery(data.id)).filter(([,value])=>value.score!==null).map(([key,value])=>[key,value.score]));const context={...(timeline?.context()||{}),code:(editor?.getValue()||'').slice(0,12000),error:lastError.slice(0,2000),problem:currentProblem?.id||'',attempts,hints:usedHints,mastery};const out=await api('tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId:data.id,mode:root.querySelector('[data-tutor-mode]').value,question,context})});if(version!==routeVersion)return;provider.textContent=out.provider==='guided'?'Local guided response — no AI model used':'Configured model response';answer.innerHTML=prose(out.answer);}catch(error){answer.textContent=error.message;}finally{button.disabled=false;}};}
  async function practice(version){const out=await api('problems?limit=100');if(version!==routeVersion)return;root.innerHTML='<h2>Connected practice</h2><p>Work in the lesson context to use its progressive hints, runnable editor and mastery checks.</p><div class="dsa-grid">'+out.items.map(problem=>`<article class="dsa-card"><h3>${html(problem.title)}</h3><p>${html(problem.difficulty)}</p>${prose(problem.statement)}<p>${topicLink(problem.lessonId||problem.lesson||problem.topic||problem.topics?.[0])}</p></article>`).join('')+'</div>';}
  async function lab(version){
    await Promise.all([loadScript('lab-viz'),loadScript('dsa-traces'),loadScript('dsa-timeline')]);if(version!==routeVersion)return;
    root.innerHTML=`<h2>Algorithm lab</h2><p>Experiment with reference algorithms through the shared timeline. Input JSON controls algorithm-specific options; large inputs are bounded to keep traces responsive.</p><div class="dsa-toolbar"><label>Algorithm<select data-alg>${catalog.topics.filter(item=>item.status==='published').map(item=>`<option value="${item.id}">${html(item.title)}</option>`).join('')}</select></label><label>Input pattern<select data-pattern><option>random</option><option>sorted</option><option>reverse sorted</option><option>nearly sorted</option><option>duplicates</option><option>adversarial</option></select></label><label>Sequence size / count n<input data-size type="number" min="0" max="24" value="8"></label>${button('Generate input','data-generate')}</div><p data-lab-note role="status"></p><div data-lab-timeline></div>`;
    let generation=0;
    async function generate(){
      const request=++generation,id=root.querySelector('[data-alg]').value;
      timeline?.dispose();timeline=null;
      const host=root.querySelector('[data-lab-timeline]');host.textContent='Loading trace…';
      try{
        const data=await lesson(id);if(version!==routeVersion||request!==generation)return;
        const kind=data.trace.kind,size=Math.max(0,Math.min(24,Math.floor(Number(root.querySelector('[data-size]').value)||0))),pattern=root.querySelector('[data-pattern]').value;
        let input=JSON.parse(JSON.stringify(data.trace.input||DSATraces.defaults[kind]));
        const sequence=['binary-search','linear-search','avl-tree','dynamic-array','linked-list'].includes(kind),counting=kind==='operation-count';
        root.querySelector('[data-pattern]').disabled=!sequence;root.querySelector('[data-size]').disabled=!sequence&&!counting;
        const values=Array.from({length:size},(_,i)=>pattern==='duplicates'?i%3:pattern==='adversarial'?i:Math.floor(Math.random()*100));
        if(pattern==='sorted'||pattern==='nearly sorted')values.sort((a,b)=>a-b);
        if(pattern==='nearly sorted'&&size>1)[values[0],values[1]]=[values[1],values[0]];
        if(pattern==='reverse sorted')values.sort((a,b)=>b-a);
        if(kind==='binary-search'){values.sort((a,b)=>a-b);input={values,target:values[Math.floor(size/2)]??0,mode:'lower_bound'};}
        if(kind==='linear-search')input={values,target:pattern==='adversarial'?-1:values[Math.floor(size/2)]??0};
        if(kind==='avl-tree')input={values,delete:values.length?[values[0]]:[]};
        if(kind==='dynamic-array')input={...input,values};
        if(kind==='linked-list')input={...input,values};
        if(counting)input={...input,n:size};
        root.querySelector('[data-lab-note]').textContent=kind==='binary-search'?'Input is sorted to satisfy binary search. Use JSON to test a violated precondition.':kind==='linear-search'?'The adversarial pattern uses an absent target, requiring a full scan.':kind==='avl-tree'?'Insertion order affects rotations; duplicates use set semantics.':kind==='dynamic-array'?'Values change the live prefix; resizing depends on size and capacity, not value order.':kind==='linked-list'?'Generated inputs reverse an ordinary chain. Configure JSON for find, insert, erase or stable sorted merge; node handles remain distinct even when values repeat.':counting?'Change mode in JSON to linear, triangular or doubling. Counters measure actual loop-body executions.':'Graph and DP inputs are configured in JSON below.';
        timeline=DSATimeline.mount(host,kind,input,id,(dimension,evidence,passed)=>DSAStore.record(id,dimension,evidence,passed));
      }catch(error){if(version===routeVersion&&request===generation)host.textContent=error.message;}
    }
    root.querySelector('[data-generate]').onclick=generate;root.querySelector('[data-alg]').onchange=generate;await generate();
  }
  function complexity(){root.innerHTML=`<h2>Complexity lab</h2><p>Theoretical growth describes a cost model; measured operation counts execute the reference search loops below. Neither predicts hardware latency by itself.</p><div class="dsa-toolbar"><label>Input size n<input data-n type="number" min="1" max="10000" value="128"></label>${button('Measure and compare','data-measure')}</div><div data-growth></div><canvas class="dsa-plot" data-plot role="img" aria-label="Growth comparison. Exact values are listed in the adjacent table."></canvas><p class="dsa-muted">Plot: log₁₀ of theoretical operation counts. Exponential and factorial curves are capped to fit the chart; the table retains a scientific/logarithmic description. Measured searches target an absent value above the maximum (worst-case linear scan).</p><div data-measured></div><h3>Why measured performance differs</h3><p class="dsa-prose">A comparison can cost one integer instruction or a long string scan. Contiguous arrays benefit from cache lines and prefetching, while pointer chasing introduces dependent loads. Allocation, branch prediction, JIT warmup, runtime overhead and input distributions change constants. Expected, amortized and worst-case claims quantify different things; none is a promise about every invocation.</p>`;
    function run(){const n=Math.max(1,Math.min(10000,Math.floor(Number(root.querySelector('[data-n]').value)||1)));root.querySelector('[data-n]').value=n;const definitions=[['1',()=>0],['log₂ n',x=>Math.log10(Math.max(1,Math.log2(x)))],['√n',x=>Math.log10(x)/2],['n',Math.log10],['n log₂ n',x=>Math.log10(x*Math.max(1,Math.log2(x)))],['n²',x=>2*Math.log10(x)],['n³',x=>3*Math.log10(x)],['2ⁿ',x=>x*Math.log10(2)],['n!',x=>{let value=0;for(let i=2;i<=x;i++)value+=Math.log10(i);return value;}]];const formatted=log=>log<8?Math.round(10**log).toLocaleString():'10^'+log.toFixed(2);root.querySelector('[data-growth]').innerHTML='<div class="dsa-scroll"><table><caption>Theoretical growth at n = '+n+'</caption><tr><th>Growth</th><th>Approximate modeled operations</th></tr>'+definitions.map(([name,fn])=>`<tr><th>${name}</th><td>${formatted(fn(n))}</td></tr>`).join('')+'</table></div>';const array=Array.from({length:n},(_,i)=>i);let linear=0,binary=0,lo=0,hi=n;const started=performance.now();for(const value of array){linear++;if(value===n)break;}const linearMs=performance.now()-started;const binaryStart=performance.now();while(lo<hi){binary++;const mid=lo+Math.floor((hi-lo)/2);if(array[mid]<n)lo=mid+1;else hi=mid;}const binaryMs=performance.now()-binaryStart;root.querySelector('[data-measured]').innerHTML=`<h3>Measured loop counts</h3><p>Linear: ${linear} comparisons. Binary lower bound: ${binary} comparisons.</p><p class="dsa-muted">Single browser run (noisy, not a benchmark): linear ${linearMs.toFixed(3)} ms; binary ${binaryMs.toFixed(3)} ms. Initialization is excluded. Use operation counts for the scaling comparison.</p>`;const canvas=root.querySelector('[data-plot]'),width=canvas.clientWidth||600,dpr=window.devicePixelRatio||1;canvas.width=width*dpr;canvas.height=300*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const styles=getComputedStyle(document.documentElement),text=styles.getPropertyValue('--text');ctx.clearRect(0,0,width,300);ctx.strokeStyle=text;ctx.beginPath();ctx.moveTo(35,15);ctx.lineTo(35,260);ctx.lineTo(width-15,260);ctx.stroke();ctx.fillStyle=text;ctx.font='12px sans-serif';ctx.fillText('log₁₀ operations',40,15);ctx.fillText('n → '+n,width-90,290);const colors=['#777','#36b','#c72','#2a7','#b4b','#f77','#aaa','#85f','#fa3'];definitions.forEach(([name,fn],i)=>{ctx.strokeStyle=colors[i];ctx.beginPath();for(let step=0;step<=60;step++){const x=1+Math.floor((n-1)*step/60),y=260-Math.min(20,fn(x))*11.5;if(step===0)ctx.moveTo(35,y);else ctx.lineTo(35+(width-55)*step/60,y);}ctx.stroke();ctx.fillStyle=colors[i];ctx.fillText(name,45+(i%5)*Math.max(48,(width-65)/5),35+Math.floor(i/5)*18);});}root.querySelector('[data-measure]').onclick=run;run();
  }
  function memory(){root.innerHTML=`<h2>Memory lab</h2><p>Compare a packed integer array with separately allocated doubly linked nodes. Addresses and cache lines here are an explicit teaching model, not your JavaScript runtime’s actual layout.</p><div class="dsa-toolbar"><label>Elements<input data-mn type="number" min="1" max="20" value="8"></label><label>Payload bytes<select data-width><option>4</option><option>8</option></select></label>${button('Show layout','data-layout')}${button('Next access','data-access')}</div><div data-memory-view></div><p data-access-note role="status"></p><details><summary>What this model omits</summary><p>Object headers, alignment, allocator metadata, garbage collection and pointer compression vary by language/runtime. CPython lists store references, not inline Python integers. C++ vector&lt;int&gt; stores integers contiguously. Linked nodes need not occupy different cache lines; this example uses dispersed allocations to demonstrate dependent loads.</p></details><p><a href="#topic/avl-tree">Inspect real tree relationships in the AVL trace</a> · <a href="#topic/knapsack">Compare a DP table with a one-row implementation</a></p>`;let access=0;function draw(){const count=Math.max(1,Math.min(20,Math.floor(Number(root.querySelector('[data-mn]').value)||1))),width=Number(root.querySelector('[data-width]').value);access%=count;root.querySelector('[data-memory-view]').innerHTML='<div class="dsa-two"><section class="dsa-panel"><h3>Packed array</h3><p>address(i) = 4096 + i × '+width+'</p><div class="dsa-cells">'+Array.from({length:count},(_,i)=>`<div class="dsa-cell ${i===access?'active':''}">${i}<small>0x${(4096+i*width).toString(16)}</small><small>line ${Math.floor(i*width/64)}</small></div>`).join('')+'</div><p>Payload '+count*width+' bytes; '+Math.ceil(count*width/64)+' modeled 64-byte cache lines.</p></section><section class="dsa-panel"><h3>Doubly linked nodes</h3><div class="dsa-cells">'+Array.from({length:count},(_,i)=>`<div class="dsa-cell ${i===access?'active':''}">${i}<small>0x${(8192+i*128).toString(16)}</small><small>prev: ${i?i-1:'null'} · next: ${i<count-1?i+1:'null'}</small></div>`).join('')+'</div><p>'+count*(width+16)+' bytes for payloads and two 8-byte links per node, before headers/padding.</p></section></div>';root.querySelector('[data-access-note]').textContent=`Access ${access}: an array computes the address directly. A list reached from its head follows ${access} next links first; each next address depends on the previous load.`;}root.querySelector('[data-layout]').onclick=()=>{access=0;draw();};root.querySelector('[data-access]').onclick=()=>{access++;draw();};draw();}
  async function route(){const version=++routeVersion;timeline?.dispose();timeline=null;editor=null;currentLesson=null;currentProblem=null;const raw=location.hash.slice(1)||'home';if(/^dsa-\d/.test(raw)){location.replace('dsa-legacy.html#'+raw);return;}if(raw==='dsa-main'){document.getElementById('dsa-main').focus();return;}const [pathname,query]=raw.split('?'),[page,id]=pathname.split('/');root.innerHTML='<p>Loading…</p>';document.querySelectorAll('.dsa-nav a').forEach(el=>{if(el.hash==='#'+page)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});try{if(page==='topic')await showTopic(decodeURIComponent(id||''),new URLSearchParams(query||''),version);else if(page==='curriculum')curriculum();else if(page==='paths')paths();else if(page==='patterns')patterns();else if(page==='compare')comparisons(decodeURIComponent(id||''));else if(page==='graph')graph();else if(page==='notes')notes();else if(page==='resources'||page==='library')resources(page==='library');else if(page==='practice')await practice(version);else if(page==='lab')await lab(version);else if(page==='complexity')complexity();else if(page==='memory')memory();else home();}catch(error){if(version===routeVersion)root.innerHTML=`<h2>Unable to load this view</h2><p role="alert">${html(error.message)}</p><p><a href="#home">Return to DSA home</a> · <a href="dsa-legacy.html">Open original lessons</a></p>`;}}
  try{catalog=await api('catalog');await Auth.ready;renderStreakPill();XP.renderPill();window.addEventListener('hashchange',route);onStateChanged(()=>{renderStreakPill();XP.renderPill();if(!currentLesson)route();});await route();}catch(error){root.innerHTML=`<h2>DSA Studio needs the application server</h2><p>${html(error.message)}</p><p>Start the existing app with <code>.venv/bin/python app.py</code>, then reload. <a href="dsa-legacy.html">Original DSA lessons</a> remain available without the server.</p>`;}
})();
